version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: quackernl/$IMAGE_NAME
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t quackernl/quacker-frontend:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag quackernl/quacker-frontend:latest quackernl/quacker-frontend:$CIRCLE_SHA1
            docker push quackernl/quacker-frontend:latest
            docker push quackernl/quacker-frontend:$CIRCLE_SHA1
      - run:
          name: Install doctl
          command: |
            cd ~
            wget https://github.com/digitalocean/doctl/releases/download/v1.57.0/doctl-1.57.0-linux-amd64.tar.gz
            tar xf ~/doctl-1.57.0-linux-amd64.tar.gz
            sudo mv ~/doctl /usr/local/bin
            doctl auth init --access-token $DO_API_TOKEN
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: echo "made it"
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
